version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: dineease_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Abc@123
      MYSQL_DATABASE: dineease 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: